# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'GRPickerControllerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GRPickerControllerExample
pod 'GRPickerViewController',:git => 'https://github.com/iOSGaurav/GRPickerViewController.git', :branch => 'master'
end
